apiVersion: batch/v1
kind: Job
metadata:
  name: jms-producer
  labels:
    app: jms-producer
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: jms-producer
      labels:
        app: jms-producer
        job-name: jms-producer
    spec:
      restartPolicy: Never
      containers:
        - name: jms-producer
          image: ghcr.io/fvaleri/jms-client:latest
          imagePullPolicy: Always
          env:
            - name: CLIENT_TYPE
              value: "producer"
            - name: PROTOCOL_NAME
              value: "amqp"
            - name: CONNECTION_URL
              value: "failover:(amqp://my-broker-all-0-svc:61617)?jms.prefetchPolicy.all=100"
            - name: CONNECTION_USERNAME
              value: "admin"
            - name: CONNECTION_PASSWORD
              value: "changeit"
            - name: QUEUE_NAME
              value: "my-queue"
            - name: MESSAGE_SIZE_BYTES
              value: "1024"
            - name: NUM_MESSAGES
              value: "100000"
            - name: PROCESSING_DELAY_MS
              value: "1000"
