apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: pool-a
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  roles:
    - broker
  storage:
    size: 100Gi
    type: persistent-claim
    deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: pool-b
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 2
  roles:
    - broker
  storage:
    size: 200Gi
    type: persistent-claim
    deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  annotations:
    strimzi.io/node-pools: enabled
spec:
  kafka:
    replicas: 3 # ignored
    # set the Kafka version
    #version: 3.6.1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      # IBP sets the lowest protocol version (downgrade is not supported)
      #inter.broker.protocol.version: "3.6"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      # this is recommended to avoid the race condition between
      # the Topic Operator and any app triggering topic auto-creation
      auto.create.topics.enable: false
    storage: # ignored
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      size: 100Gi
      type: persistent-claim
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
    template:
      topicOperatorContainer:
        env:
          # disable the use of finalizers to control topic deletion
          - name: STRIMZI_USE_FINALIZERS
            value: "false"
  cruiseControl: {}
