apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: kafka-producer
      labels:
        app: kafka-producer
        job-name: kafka-producer
    spec:
      restartPolicy: Never
      containers:
        - name: kafka-producer
          image: ghcr.io/fvaleri/kafka-client:latest
          imagePullPolicy: Always
          env:
            - name: CLIENT_TYPE
              value: "producer"
            - name: BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap:9092"
            - name: SECURITY_PROTOCOL
              value: "PLAINTEXT"
            - name: TOPIC_NAME
              value: "my-topic"
            - name: MESSAGE_SIZE_BYTES
              value: "1024"
            - name: NUM_MESSAGES
              value: "100000"
            - name: PROCESSING_DELAY_MS
              value: "1000"
