apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-txn
spec:
  replicas: 3
  serviceName: kafka-txn
  selector:
    matchLabels:
      app: kafka-txn
  template:
    metadata:
      labels:
        app: kafka-txn
    spec:
      containers:
        - name: kafka-txn
          image: ghcr.io/fvaleri/kafka-txn:latest
          env:
            - name: BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap:9092"
            - name: GROUP_ID
              value: "my-group"
            - name: INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INPUT_TOPIC
              value: "input-topic"
            - name: OUTPUT_TOPIC
              value: "output-topic"
