spec:
  replicas: 1
  template:
    spec:
      containers:
        - resources:
            requests:
              cpu: 0.5
              memory: 128Mi
            limits:
              cpu: 1.0
              memory: 256Mi
